-- GRANTS
GRANT USAGE ON SCHEMA "c-07-bengkalis" TO oltp_user;
GRANT SELECT ON ALL TABLES IN SCHEMA "c-07-bengkalis" TO oltp_user;
GRANT USAGE ON SCHEMA "c-08-rokan-hilir" TO oltp_user;
GRANT SELECT ON ALL TABLES IN SCHEMA "c-08-rokan-hilir" TO oltp_user;
GRANT USAGE ON SCHEMA "c-09-meranti" TO oltp_user;
GRANT SELECT ON ALL TABLES IN SCHEMA "c-09-meranti" TO oltp_user;
GRANT USAGE ON SCHEMA "d-10-rokan-hulu" TO oltp_user;
GRANT SELECT ON ALL TABLES IN SCHEMA "d-10-rokan-hulu" TO oltp_user;
GRANT USAGE ON SCHEMA "d-11-pekanbaru" TO oltp_user;
GRANT SELECT ON ALL TABLES IN SCHEMA "d-11-pekanbaru" TO oltp_user;
GRANT USAGE ON SCHEMA "d-12-dumai" TO oltp_user;
GRANT SELECT ON ALL TABLES IN SCHEMA "d-12-dumai" TO oltp_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA "c-07-bengkalis" GRANT SELECT ON TABLES TO oltp_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA "c-08-rokan-hilir" GRANT SELECT ON TABLES TO oltp_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA "c-09-meranti" GRANT SELECT ON TABLES TO oltp_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA "d-10-rokan-hulu" GRANT SELECT ON TABLES TO oltp_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA "d-11-pekanbaru" GRANT SELECT ON TABLES TO oltp_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA "d-12-dumai" GRANT SELECT ON TABLES TO oltp_user;
